#!/usr/bin/env python3
# --------------------------------------------------------------------
# Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# --------------------------------------------------------------------
"""Generate docs/README.md policy catalog table from docs/<policy>/<version>/metadata.json.

The table is injected into scripts/README.md.template between the
<!-- POLICY_TABLE_START --> and <!-- POLICY_TABLE_END --> markers.

Usage:
  generate-policy-catalog.py           # write docs/README.md
  generate-policy-catalog.py --validate # exit 1 if docs/README.md is out of date
"""

import json
import re
import sys
from pathlib import Path

DOCS_DIR = Path(__file__).parent.parent / "docs"
TEMPLATE = Path(__file__).parent / "README.md.template"
OUTPUT = DOCS_DIR / "README.md"

TABLE_START = "<!-- POLICY_TABLE_START -->"
TABLE_END = "<!-- POLICY_TABLE_END -->"


def latest_version(policy, versions):
    valid = [v for v in versions if re.match(r"^v\d+\.\d+$", v)]
    invalid = set(versions) - set(valid)
    for v in invalid:
        print(f"warning: {policy}: skipping unrecognised version directory '{v}'", file=sys.stderr)
    if not valid:
        raise ValueError(f"{policy}: no valid vX.Y version directories found in {versions}")
    return sorted(valid, key=lambda v: [int(x) for x in v.lstrip("v").split(".")])[-1]


def first_sentence(text):
    flat = re.sub(r"\s+", " ", text.strip())
    if not flat:
        return ""
    m = re.search(r"^(.+?[.!?])\s", flat)
    return m.group(1) if m else flat.split(".")[0].strip() + "."


def build_table_rows():
    policies = []

    for entry in sorted(DOCS_DIR.iterdir()):
        if not entry.is_dir():
            continue
        versions = [d.name for d in entry.iterdir() if d.is_dir()]
        if not versions:
            continue

        ver = latest_version(entry.name, versions)
        meta_path = entry / ver / "metadata.json"
        if not meta_path.exists():
            continue

        try:
            with open(meta_path) as f:
                meta = json.load(f)
        except json.JSONDecodeError as e:
            print(f"warning: skipping {meta_path}: malformed JSON: {e}", file=sys.stderr)
            continue

        docs_subdir = entry / ver / "docs"
        doc_files = sorted(docs_subdir.glob("*.md")) if docs_subdir.exists() else []
        doc_file = doc_files[0].name if doc_files else None
        link = f"./{entry.name}/{ver}/docs/{doc_file}" if doc_file else None

        policies.append({
            "name": meta.get("displayName", entry.name),
            "link": link,
            "categories": meta.get("categories", []),
            "description": first_sentence(meta.get("description", "")),
        })

    policies.sort(key=lambda p: p["name"].lower())

    lines = [
        "| Policy | Categories | Description |",
        "|--------|------------|-------------|",
    ]

    for p in policies:
        name_cell = f"[{p['name']}]({p['link']})" if p["link"] else p["name"]
        cats = ", ".join(p["categories"])
        lines.append(f"| {name_cell} | {cats} | {p['description']} |")

    return "\n".join(lines)


def build_catalog():
    if not TEMPLATE.exists():
        print(f"error: template not found: {TEMPLATE}", file=sys.stderr)
        sys.exit(1)

    template = TEMPLATE.read_text()

    if TABLE_START not in template or TABLE_END not in template:
        print(f"error: {TEMPLATE} must contain '{TABLE_START}' and '{TABLE_END}' markers", file=sys.stderr)
        sys.exit(1)

    table = build_table_rows()
    replacement = f"{TABLE_START}\n{table}\n{TABLE_END}"
    content = re.sub(
        re.escape(TABLE_START) + r".*?" + re.escape(TABLE_END),
        replacement,
        template,
        flags=re.DOTALL,
    )
    header = (
        "<!--\n"
        "THIS FILE IS AUTO-GENERATED.\n"
        "\n"
        "Do not edit this file directly.\n"
        "Generated by: scripts/generate-policy-catalog.py\n"
        "-->\n\n"
    )
    return header + content


def main():
    check_mode = "--validate" in sys.argv
    content = build_catalog()

    if check_mode:
        if not OUTPUT.exists():
            print(f"error: {OUTPUT} does not exist. Run 'make generate-catalog' to create it.")
            sys.exit(1)
        current = OUTPUT.read_text()
        if current == content:
            print(f"{OUTPUT} is up to date.")
        else:
            print(f"error: {OUTPUT} is out of date. Run 'make generate-catalog' to regenerate it.")
            sys.exit(1)
    else:
        OUTPUT.write_text(content)
        print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
